spring.application.name=ratelimiter

ratelimit.algorithm=sliding-window
ratelimit.limit=10
ratelimit.window-millis=60000

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true